### PR TITLE
The computer will check your input to make sure it's valid

### PR DESCRIPTION
**Pull request by Mega-Roman**
Added input checking

### CODE REVIEW

**Review by RhysDaBoi — APPROVED** [review]
Played, Looks great and works very well :)

**Comment by Mega-Roman** [comment]
@RhysDaBoi I have adapted the code to work with yours, can you please review it :)?

**Review by RhysDaBoi — APPROVED** [review]
Played, looks good and works

**Review by professionalSkillIssue — APPROVED** [review]
tested - works fine.

**Pull request merged**
